import Footer from "@/components/Footer";
import Nav from "@/components/Nav";
import Table from "@/components/Table";

export const metadata = {
	title: 'Products',
	description: 'Generated by create next app',
}

const products = {
	column: ['', 'Title', 'Subtitle', 'Quality', 'Desc'],
	data: [
		{
			'title': 'Cube',
			'image': '/cube_2.png',
			'subtitle': 'Shisha Briquette',
			'quality': 
				[
					{'name': 'Super Premium', 'ash': '1.9% - 2.2%'},
					{'name': 'Premium', 'ash': '2.2% - 2.5%'},
					{'name': 'Gold', 'ash': '2.5% - 3.5%'},
					{'name': 'Regular', 'ash': '4.5% - 7%'},
				],
			'desc': 'Inner Plastic 1KG, Inner Box 1KG, Outer Box 10KG'
		},
		{
			'title': 'Pillow',
			'image': '/pillow.png',
			'subtitle': 'BBQ Briquette',
			'quality': 
				[
					{'name': 'A', 'ash': '3% - 5%'},
					{'name': 'B', 'ash': '7% - 8%'},
					{'name': 'C', 'ash': '10% - 12%'},
					{'name': 'D', 'ash': 'Up To 18%'},
				],
			'desc': 'Inner Plastic, Inner Box 10KG'
		},
		{
			'title': 'Hexagon',
			'image': '/hex.png',
			'subtitle': 'BBQ Briquette',
			'quality': 
				[
					{'name': 'A', 'ash': '3% - 5%'},
					{'name': 'B', 'ash': '7% - 8%'},
					{'name': 'C', 'ash': '10% - 12%'},
					{'name': 'D', 'ash': 'Up To 18%'},
				],
			'desc': 'Inner Plastic, Inner Box 10KG'
		},
	],
};

function Products() {
	return (
		<main className="flex min-h-screen flex-col items-center bg-black">
			<div className="w-full top-0 z-20 fixed">
				<Nav />
			</div>

			<section className="my-12"></section>

			<div>
				<Table data={products} />
			</div>

			<section className="my-10 md:my-20" id='contact'></section>

			<Footer />
		</main>
	)
}

export default Products;
